[general]
import = [
"~/.config/alacritty/Themes/gruvbox_hard_dark.toml"
#"~/.config/alacritty/Themes/gruvbox_medium_dark.toml"
#"~/.config/alacritty/Themes/gruvbox_soft_dark.toml"
#"~/.config/alacritty/Themes/gruvbox_material_hard_light.toml"
#"~/.config/alacritty/Themes/gruvbox_material_medium_light.toml"
#"~/.config/alacritty/Themes/gruvbox_material_soft_light.toml"
]

[font]
size = 9.0

[font.normal]
family = "JetBrains Mono Nerd Font"

[window]
opacity = 0.90
decorations = "none"

[window.padding]
x = 2
y = 2

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
unfocused_hollow = false

[keyboard]
bindings = [
    { key = "C",              action = "Copy",             mods = "Control|Shift" },
    { key = "V",              action = "Paste",            mods = "Control|Shift" },
    { key = "Plus",           action = "IncreaseFontSize", mods = "Control"       },
    { key = "Minus",          action = "DecreaseFontSize", mods = "Control"       },
    { key = "Key0",           action = "ResetFontSize",    mods = "Control"       },
]
