- name: Set up Arch Linux system
  hosts: localhost
  become: true

  vars:
    dotfiles_dir: "{{ lookup('env', 'HOME')}}/.dotfiles"
    pacman_packages:
      cli:
        - git
        - stow
        - zsh

  tasks:
    - name: Update pacman cache
      tags: [pacman]
      pacman:
        update_cache: true

    - name: Install CLI packages
      tags: [pacman]
      pacman:
        name: "{{ pacman_packages.cli }}"
        state: present

    - name: Change default shell to zsh
      tags: [zsh]
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh

    - name: Stow dotfiles
      tags: [stow]
      ansible.builtin.shell:
        chdir: "{{ dotfiles_dir  }}"
        cmd: "stow --verbose {{ item }}"
      register: stow_out
      changed_when: 'stow_out.stderr is search("LINK: ")'
      with_items:
        - git
        - zsh
