# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = ignore_mazimize_requests
    match:class = ".*"
    suppress_event = ["maximize"]
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix_dragging_issues
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
    no_focus = yes
}
