# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = ignore_mazimize_requests
    match:class = ".*"
    suppress_event = ["maximize"]
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix_dragging_issues
    match:class = "^$"
    match:title = "^$"
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
    no_focus = yes
}

# Force steam windows to float (fixes tiled layout crashes and dropdown issues)
windowrule = match:class ^(steam)$, float on
windowrule = match:class ^(steamwebhelper)$, float on
windowwrule = match:title ^(.*dropdown.*)$, stay_focused on

# Fix for blurry/incorrect Xwayland scaling
xwayland {
    force_zero_scaling = true
}

# If using an Nvidia GPU, use these variables:
env = __GL_VRR_ALLOWED,1
env = WLR_DRM_NO_ATOMIC,1
