# Colors (Gruvbox Medium Dark)

[colors.primary]
background = '#282828'
foreground = '#d4be98'

[colors.normal]
black   = '0x3c3836'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.bright]
black   = '0x3c3836'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'
