splash = false

wallpaper {
    monitor = DP-3
    path = /home/alle/Pictures/wallpaper2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/alle/Pictures/wallpaper2.jpg
    fit_mode = cover
}
